

default_platform(:android)

platform :android do
  desc "New Android Version Build for the App"
  lane :firebase_distribution do
    #gradle(task: "test")
    sh "flutter clean"
    sh "flutter build apk --release --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:445576248179:android:e48e685332dce8f72ce306",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    apk_path: "../build/app/outputs/apk/release/app-release.apk",
    testers: "mkelsafty1838@gmail.com",
    release_notes: "First Android Version Build for the App",
  )
  end
end
